version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    volumes:
      - ${PWD}/scripts/credential_loader.sh:/opt/keycloak/credential_loader.sh
    environment:
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    secrets:
      - kc-admin-user
      - kc-admin-password
    ports:
      - "8080:8080"
    entrypoint: ["/bin/sh", "-c"]
    command: ["chmod +x /opt/keycloak/credential_loader.sh && /opt/keycloak/credential_loader.sh start-dev"]
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /auth/health HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 30s
      timeout: 10s
      retries: 3

secrets:
  kc-admin-user:
    file: ./secrets/kc-admin-user.txt
  kc-admin-password:
    file: ./secrets/kc-admin-password.txt